### ISSUE TITLE
Create thumbnails and thumbnails template / documentation for our YT videos

### ISSUE THREAD

**Issue by lenucksi** [InnerSourceCommons/InnerSourceLearningPath#243]
## Rationale + explanation

YouTube offers us to select a visually appealing thumbnail (a "frame") for our videos. 
@RJPlog has presented some great thoughts and template material for them:
* [explanation](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/8cbb02beb41c145ea6bee5235de5c0c206fa8533/assets/thumbnails/thumbnail.asciidoc)
* [example](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/8cbb02beb41c145ea6bee5235de5c0c206fa8533/assets/thumbnails/example5.jpg)

## ToDo
- [x] Create PR for the template material and explanation @RJPlog 
- [x] Actually create the frames
- [x] Apply the frames to the respective videos.
  - [x] Introduction
  - [x] Trusted Comitter
  - [x] Contributor
  - [x] Product Owner

**Comment by RJPlog** [comment]
I just created a PR (#245) to upload the template. Within the rationale document you can find also an example. Please feel free to add your comments :-).

**Comment by RJPlog** [comment]
I finished  creating all the thumbnails now and applied them to the videos. 
Since we changed the fonts in our template I have to do a final update on the template yet.

Is there a way to mark the done topics in the checkboxes?

**Comment by lenucksi** [comment]
> I finished creating all the thumbnails now and applied them to the videos.
:tada: 

> Is there a way to mark the done topics in the checkboxes?
I've added a few checkboxes for the individual section to the top - you should be able to just check them off. If not, let me know.

**Comment by rrrutledge** [comment]
Sounds like great progress, @RJPlog.

**Comment by lenucksi** [comment]
Anything keeping us from closing this now that #264 is merged too?

**Comment by rrrutledge** [comment]
Looks good to me.

**Comment by lenucksi** [comment]
Looks done to me now.
